Monitoring:
  Addr: "0.0.0.0:8126"
  Prefix: "rider/"
Logging:
  Level: info
  Format: json


Server:
  Port: 8080

Messaging:
  Emission:
    Address: 0.0.0.0:4150
    MaxInFlight: 25
    Topic: rider.trips
